### ISSUE TITLE
StemApp without Me app

### ISSUE THREAD

**Issue by maxvisser** [TeamSnowflake/research-and-development#2]
# poc001-make-vote-without-me-app
## Background / Context
https://github.com/teamforus/research-and-development/issues/87

Can you guys look at this issue, maybe you guys can solve it with a small adjustment to the app.

**Comment by KevinH96** [comment]
N.a.v. gesprek met Patrick besloten om nieuwe issues die niet noodzakelijk zijn niet meer aan te nemen voor de huidige tijdspanne van het project. Kan eventueel na 22-06-2018 wel overlegd worden, maar wordt voor nu even genegeerd,
